### ISSUE TITLE
Support for en-CA language

### ISSUE THREAD

**Issue by R4ZZB3RRY** [fabianosan/HomeAssistantAssistAWS#2]
Hi!  I want to thank you so much for creating this.  It works awesome and is amazing.  I just wanted to ask if you could update the code to include support for Canada English.  This works flawlessly when using the United States English but when I change my Amazon devices to the USA language it is not compatible with the Canadian Features.  

 If this is to difficult for I would really appreciate it if you could do this.  I would be willing to send you a little bit of cash.

Thanks,

Mitchell

P.S.  Sorry I dont have an en-CA.lang file

**Comment by fabianosan** [comment]
Sure.
I'll do.

**Comment by R4ZZB3RRY** [comment]
Thanks your the best!  Where are you from?  Do you want me to send you some cash for your trouble?  Euro?  USD?

**Comment by fabianosan** [comment]
Need nothing.
Thank you!

en-CA added in the release 0.5
